### ISSUE TITLE
Different "single" portfolio templates per category

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Portfolio-Extension#1]
I was wondering, while overriding the portfolio views, how to have different templates for specific portfolio categories.

Right now what I'm doing, is adding this to `single.php` : 

```
$categories = get_the_terms(get_the_ID(), fw()->extensions->get('portfolio')->get_taxonomy_name());
$cat_array=array();
foreach($categories as $c)
{
    switch($c->slug)
    {
        case 'works':
        include 'single-works.php';
        return;
    }
}
```

This example will include a view `works.php` I created if the "works" category belongs to the current post.
I guess I could use the filter `add_filter('single_template', 'return_some_single_category_template');` in my functions.php, but I would have to include this for all my child themes.

I was wondering if they was a cleaner/automatic way to do it, like creating a file called `single-works.php`, that is automatically included (I guess similar to the way [WP does it](http://codex.wordpress.org/Post_Type_Templates))

What do you think?

**Comment by sergiubagrin** [comment]
Sorry for the late reply.

I added it to Next Up list.

**Comment by erralb** [comment]
Thanks!
