### ISSUE TITLE
Assets in portfolio (and extensions in general)

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Portfolio-Extension#2]
Hi, and happy new year :)

While extending the portfolio extension in a child theme, I came across cases where the design of a project did not require a slider, or required a different slider than Nivo Slider.

The problem is that the default assets are automatically added to the page, even when you don't need them.
As a result I have the nivo slider css et js included in the page when I don't need them at all.
This makes the page heavier and generates more requests on the server.

I realize I can recreate these files in my child theme and then empty them, so these empty files would take less bandwidth, but the http requests would still be there.

I would suggest a static assets configuration file, instead of just loading everything that's in the static folder. It would give more control and better performance when extending the extensions.

What do you think @moldcraft @GheorgheP ?

**Comment by ghost** [comment]
Hello,
Just overwrite `portfolio/static.php` by creating `framework-customizations/extensions/portfolio/static.php`. The file can be empty or enqueue your own assets in it.

http://unyson-docs.themefuse.com/en/latest/extensions/directory-structure.html#content
If docs has some unclarities and you know how to improve it, you can make a pull request https://github.com/ThemeFuse/Unyson-Documentation

**Comment by erralb** [comment]
Damn sorry I missed that!
Thanks for the answer, I think the doc is clear... I just missed it!
