### ISSUE TITLE
can't add tags to portfolio custom post

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Portfolio-Extension#3]
Hi,

When I add `'taxonomies' => array('post_tag')` to the `_action_register_post_type` in `unyson/framework/extensions/portfolio/class-fw-extension-portfolio.php` , the tags are added to the custom post and I can see the tags in the project edit form.

But if I duplicate `class-fw-extension-portfolio.php` into my child theme, into `framework-customizations/extensions/portfolio/`, and then add `'taxonomies' => array('post_tag')` to the `_action_register_post_type` function, it does not work.

Any idea how I can solve this without modifying unyson's core ?
Maybe it should be an option of the unyson porftolio extension ... ?

**Comment by ghost** [comment]
> But if I duplicate `class-fw-extension-portfolio.php` into my child theme

You can't overwrite extension class.

> Any idea how I can solve this?
> Maybe it should be an option of the unyson porftolio extensions ... ?

We will come back with a response soon.

**Comment by erralb** [comment]
Then can this be achieved without touching the core ?

As a quick fix I edited it into the core, but I'm afraid it might be deleted by future updates...

**Comment by GheorgheP** [comment]
Hi,

I'm not sure I understand your request, but this has to be simple.

Create the `hooks.php` file in `framework-customizations/extensions/portfolio`, and add this code:

``` php
<?php if ( ! defined( 'FW' ) ) {
    die( 'Forbidden' );
}

function _action_add_portfolio_tags() {
    $labels = array(
        'name'              => __( 'Tags', 'fw' ),
        'singular_name'     => __( 'Tag', 'fw' ),
        'search_items'      => __( 'Search Tag', 'fw' ),
        'all_items'         => __( 'All Tags', 'fw' ),
        'parent_item'       => __( 'Parent Tag', 'fw' ),
        'parent_item_colon' => __( 'Parent Tag', 'fw' ) . ':',
        'edit_item'         => __( 'Edit Tag', 'fw' ),
        'update_item'       => __( 'Update Tag', 'fw' ),
        'add_new_item'      => __( 'Add New Tag', 'fw' ),
        'new_item_name'     => __( 'New Tag Name', 'fw' ),
        'menu_name'         => __( 'Tag', 'fw' ),
    );

    $args = array(
        'hierarchical'      => false,
        'labels'            => $labels,
        'show_ui'           => true,
        'show_admin_column' => true,
        'show_in_nav_menus' => false,
        'query_var'         => true,
        'rewrite'           => array( 'slug' => 'tag' ),
    );

    register_taxonomy( 'tag', array( 'fw-portfolio' ), $args );
}

add_action( 'init', '_action_add_portfolio_tags' );
```

**Comment by erralb** [comment]
Hi, thanks for that it worked!
