### ISSUE TITLE
PHP Strict Standards

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Portfolio-Extension#5]
Hi, here is a non blocking error, but just so you guys know :

`PHP Strict Standards:  Only variables should be assigned by reference in  /plugins/unyson/framework/extensions/portfolio/class-fw-extension-portfolio.php on line 46`

Removing the `&` sign `$post = &get_post($id);` to  `$post = get_post($id);` solves the problem for me

**Comment by GheorgheP** [comment]
Hi,

Sorry for big delay,

Here's the line [#46](https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/master/class-fw-extension-portfolio.php#L46)

There is no any function passed by reference.

**Comment by GheorgheP** [comment]
Did not get any reply
