### ISSUE TITLE
Warning after activating Portfolio extension

### ISSUE THREAD

**Issue by MrNoSox** [ThemeFuse/Unyson-Portfolio-Extension#7]
No clue what this means, but just wanted to post it incase it was an issue. I'm sure it's something that I haven't set-up correctly. 

This is a multi-site install and I'm using the scratch-child theme. After activating the portfolio, this shows up at the top of the Unyson Extensions screen.

---

Warning: include(): Filename cannot be empty in /home/*mydirectory/public_html/jeffblakemore.com/wp-content/themes/scratch-parent/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Filename cannot be empty in /home/*mydirectory/public_html/jeffblakemore.com/wp-content/themes/scratch-parent/framework-customizations/extensions/portfolio/static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/*mydirectory/public_html/jeffblakemore.com/wp-content/themes/scratch-parent/framework-customizations/extensions/portfolio/static.php on line9

---

**Comment by MrNoSox** [comment]
I created a portfolio item to see if that would do anything. It didn't. This is also showing up on the homepage...

![screen shot 2015-04-27 at 1 45 39 pm](https://cloud.githubusercontent.com/assets/3986335/7353733/db4810ce-ece3-11e4-8670-cccdb93625b6.png)

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson/issues/414

**Comment by MrNoSox** [comment]
Thanks moldcraft, I downloaded the Scratch Theme from the unyson.io today and installed it. Is that not the latest version?

**Comment by ghost** [comment]
[It's not the latest version](http://static.md/2c59f625a07532a25ca7187c88edb5bd.png), sorry about that. We will create a new release soon.

Download it from [here](http://static.md/66c0fb82168c925df6975fe4438d59f2.png).
